spring:
  application:
    name: enrollment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/${ENROLLMENT_DB_NAME:enrollment_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # JWT validation via Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/edtech
          jwk-set-uri: http://localhost:8080/realms/edtech/protocol/openid-connect/certs

server:
  port: 8081
