services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
      POSTGRES_MULTIPLE_DATABASES: enrollment_db,academic_db,assessment_db,finance_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh

volumes:
  postgres_data:
